<h2>New entry</h2>
<form method="post" name="test" class="needs-validation was-validated">
  <div class="form-group">
    <label for="field1">Title</label>
    <input type="text" name="title" class="form-control col-sm" id="field1" placeholder="My task ..." required />
  </div>
  <div class="form-group">
    <label for="field1">Content</label>
    <textarea name="desc" class="form-control col-sm" id="field2" rows="5" placeholder="Description of task ..." required></textarea>
  </div>
  <div class="form-group">
    <label for="field1">Comments</label>
    <input type="text" name="comments" class="form-control col-sm" id="field3" placeholder="My comments (optional)" />
  </div>
  <div class="form-group">
    <button name="submit" type="submit" class="btn btn-primary col-sm-2">Submit</button>
  </div>
</form>