<?php
require_once "../src/classes/BdFetcher.php";
$entries = BdFetcher::fetchAllArchived();

?>
<script src="https://kit.fontawesome.com/c1884176b5.js" crossorigin="anonymous"></script>

<h2>All archived entries (<?php echo count($entries) ?> item<?php if (count($entries) > 1) { echo "s";} ?>)</h2>

<?php

if (!$entries) {
  echo "No entries found.";
}
foreach ($entries as $row) : ?>

  <form method="post" name="test" class="needs-validation was-validated">
    <input type="hidden" name="id" value="<?php echo $row['id'] ?>" />
    <div class="form-group">
      <div class="row">
        <div class="col-sm-5">
          <?php if ($row['edited'] == 'Y') { echo "<b data-toggle='tooltip' title=' Edited on " . $row['edit_time'] . "'>(E)&nbsp</b>"; } echo $row['entry_time'] ?>
        </div>
        <div class="col-sm text-right">
          <button class="btn btn-info btn-sm" onclick="return confirm('Are you sure you want to move this entry back to the active entries page?')" type="submit" name="unarchive">Unarchive</button>
          <button class="btn btn-warning btn-sm" onclick="return confirm('Are you sure you want to permanently delete this entry? (This action is irreversible!)')" type="submit" name="delete_entry_archived">Delete</button>
        </div>
      </div>
      <input type="text" name="title" class="form-control col-sm" id="field1" value="<?php echo $row['title'] ?>" disabled />
    </div>
    <div class="form-group">
      <label for="field1">Content</label>
      <textarea name="desc" class="form-control col-sm" id="field2" rows="5" disabled><?php echo $row['description'] ?></textarea>
    </div>
    <div class="form-group">
      <label for="field1">Comments</label>
      <input type="text" name="comments" class="form-control col-sm" id="field3" value="<?php echo $row['observations'] ?>" disabled />
    </div>
    <hr>
  </form>

<?php endforeach; ?>